#!/bin/sh

AUTH_KEY="tskey-a"

cat > "/etc/config/network" << 'EOF'
config interface 'loopback'
	option device 'lo'
	option proto 'static'
	list ipaddr '127.0.0.1/8'

config globals 'globals'
	option ula_prefix 'fdbe:29dd:f908::/48'
	option packet_steering '1'

config device
	option name 'br-hub'
	option type 'bridge'
	list ports 'lan1'

config device
	option name 'br-home'
	option type 'bridge'
	list ports 'lan2'

config device
	option name 'br-guest'
	option type 'bridge'

config device
	option name 'br-things'
	option type 'bridge'
	list ports 'lan3'

config interface 'server'
	option device 'br-hub'
	option proto 'static'
	list ipaddr '192.168.11.1/24'
	option ip6assign '60'

config interface 'home'
	option device 'br-home'
	option proto 'static'
	list ipaddr '192.168.21.1/24'

config interface 'things'
	option device 'br-things'
	option proto 'static'
	list ipaddr '192.168.31.1/24'

config interface 'guest'
	option device 'br-guest'
	option proto 'static'
	list ipaddr '192.168.100.1/24'

config interface 'wan'
	option device 'wan'
	option proto 'dhcp'
EOF

cat > "/etc/config/wireless" << EOF

config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/soc/platform/18000000.wifi'
	option channel '1'
	option band '2g'
	option htmode 'HE20'
	option disabled '0'

config wifi-iface 'home_radio0'
	option device 'radio0'
	option network 'home'
	option mode 'ap'
	option ssid 'Home'
	option encryption 'psk2'
	option key 'X9dV7FqC1s'
	option ieee80211r '1'

config wifi-iface 'things_radio0'
	option device 'radio0'
	option network 'things'
	option mode 'ap'
	option ssid 'Things'
	option encryption 'psk2'
	option key 'hQ39bR5xw2'
	option hidden '1'

config wifi-iface 'tuya_radio0'
	option device 'radio0'
	option network 'things'
	option mode 'ap'
	option ssid 'REFAZ HOME-EX'
	option encryption 'psk2'
	option key 'amhamzah'
	option hidden '1'

config wifi-iface 'duplicate_radio0'
	option device 'radio0'
	option network 'guest'
	option mode 'ap'
	option ssid 'REFAZ HOME'
	option encryption 'psk2'
	option key 'amhamzah'
	option hidden '1'

config wifi-iface 'guest_radio0'
	option device 'radio0'
	option network 'guest'
	option mode 'ap'
	option ssid 'Guest'
	option encryption 'psk2'
	option key 'qwertyui5678'
	option isolate '1'
	option ieee80211r '1'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'platform/18000000.wifi+1'
	option channel '36'
	option band '5g'
	option htmode 'HE80'
	option disabled '0'

config wifi-iface 'home_radio1'
	option device 'radio1'
	option network 'home'
	option mode 'ap'
	option ssid 'Home'
	option encryption 'psk2'
	option key 'X9dV7FqC1s'
	option ieee80211r '1'

config wifi-iface 'server_radio1'
	option device 'radio1'
	option network 'server'
	option mode 'ap'
	option ssid 'Servers'
	option encryption 'psk2'
	option key 'hQ39bFqC1s'
	option hidden '1'
EOF

cat > "/etc/config/dhcp" << EOF
config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option filterwin2k '0'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/in/'
	option domain 'in'
	option expandhosts '1'
	option nonegcache '0'
	option cachesize '1000'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option nonwildcard '1'
	option localservice '1'
	option ednspacket_max '1232'
	option filter_aaaa '0'
	option filter_a '0'

config dhcp 'home'
	option interface 'home'
	option start '2'
	option limit '25'
	option leasetime '7d'

config dhcp 'server'
	option interface 'server'
	option start '2'
	option limit '25'
	option leasetime '4w'

config dhcp 'things'
	option interface 'things'
	option start '11'
	option limit '60'
	option leasetime '2w'

config dhcp 'guest'
	option interface 'guest'
	option start '101'
	option limit '50'
	option leasetime '2h'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'
EOF


cat > "/etc/config/firewall" << 'EOF'
config defaults
        option input 'REJECT'
        option output 'ACCEPT'
        option forward 'REJECT'
        option synflood_protect '1'

config zone
        option name 'wan'
        option input 'REJECT'
        option output 'ACCEPT'
        option forward 'REJECT'
        option masq '1'
        option mtu_fix '1'
        list network 'wan'

config rule
        option name 'Allow-DHCP-Renew'
        option src 'wan'
        option proto 'udp'
        option dest_port '68'
        option target 'ACCEPT'
        option family 'ipv4'

config rule
        option name 'Allow-Ping'
        option src 'wan'
        option proto 'icmp'
        option icmp_type 'echo-request'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-IGMP'
        option src 'wan'
        option proto 'igmp'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-DHCPv6'
        option src 'wan'
        option proto 'udp'
        option dest_port '546'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-MLD'
        option src 'wan'
        option proto 'icmp'
        option src_ip 'fe80::/10'
        list icmp_type '130/0'
        list icmp_type '131/0'
        list icmp_type '132/0'
        list icmp_type '143/0'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-Input'
        option src 'wan'
        option proto 'icmp'
        list icmp_type 'echo-request'
        list icmp_type 'echo-reply'
        list icmp_type 'destination-unreachable'
        list icmp_type 'packet-too-big'
        list icmp_type 'time-exceeded'
        list icmp_type 'bad-header'
        list icmp_type 'unknown-header-type'
        list icmp_type 'router-solicitation'
        list icmp_type 'neighbour-solicitation'
        list icmp_type 'router-advertisement'
        list icmp_type 'neighbour-advertisement'
        option limit '1000/sec'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-Forward'
        option src 'wan'
        option dest '*'
        option proto 'icmp'
        list icmp_type 'echo-request'
        list icmp_type 'echo-reply'
        list icmp_type 'destination-unreachable'
        list icmp_type 'packet-too-big'
        list icmp_type 'time-exceeded'
        list icmp_type 'bad-header'
        list icmp_type 'unknown-header-type'
        option limit '1000/sec'
        option family 'ipv6'
        option target 'ACCEPT'

config zone
        option name 'server'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        list network 'server'

config rule
        option name 'Allow-DHCP-server'
        option src 'server'
        option proto 'udp'
        option dest_port '67 68'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-DNS-server'
        option src 'server'
        option proto 'tcp udp'
        option dest_port '53'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-server'
        option src 'server'
        option proto 'icmp'
        option family 'ipv6'
        option target 'ACCEPT'

config forwarding
        option src 'server'
        option dest 'wan'

config zone
        option name 'home'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        list network 'home'

config rule
        option name 'Allow-DHCP-home'
        option src 'home'
        option proto 'udp'
        option dest_port '67 68'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-DNS-home'
        option src 'home'
        option proto 'tcp udp'
        option dest_port '53'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-home'
        option src 'home'
        option proto 'icmp'
        option family 'ipv6'
        option target 'ACCEPT'

config forwarding
        option src 'home'
        option dest 'wan'

config forwarding
        option src 'server'
        option dest 'home'

config forwarding
        option src 'home'
        option dest 'server'

config zone
        option name 'things'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        list network 'things'

config rule
        option name 'Allow-DHCP-things'
        option src 'things'
        option proto 'udp'
        option dest_port '67 68'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-DNS-things'
        option src 'things'
        option proto 'tcp udp'
        option dest_port '53'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-things'
        option src 'things'
        option proto 'icmp'
        option family 'ipv6'
        option target 'ACCEPT'

config forwarding
        option src 'things'
        option dest 'wan'

config forwarding
        option src 'server'
        option dest 'things'

config forwarding
        option src 'things'
        option dest 'server'

config zone
        option name 'guest'
        option input 'REJECT'
        option output 'ACCEPT'
        option forward 'REJECT'
        list network 'guest'

config rule
        option name 'Allow-DHCP-guest'
        option src 'guest'
        option proto 'udp'
        option dest_port '67 68'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-DNS-guest'
        option src 'guest'
        option proto 'tcp udp'
        option dest_port '53'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-guest'
        option src 'guest'
        option proto 'icmp'
        option family 'ipv6'
        option target 'ACCEPT'

config forwarding
        option src 'guest'
        option dest 'wan'

config zone
        option name 'tailscale'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option masq '1'
        list device 'tailscale0'

config forwarding
        option src 'tailscale'
        option dest 'wan'

config forwarding
        option src 'server'
        option dest 'tailscale'

config forwarding
        option src 'tailscale'
        option dest 'server'

config forwarding
        option src 'home'
        option dest 'tailscale'

config forwarding
        option src 'tailscale'
        option dest 'home'

config forwarding
        option src 'things'
        option dest 'tailscale'

config forwarding
        option src 'tailscale'
        option dest 'things'
EOF

cat > "/etc/config/system" << EOF
config system
        option hostname 'axt'
        option timezone 'IST-5:30'
        option zonename 'Asia/Kolkata'
        option ttylogin '0'
        option log_size '64'
        option urandom_seed '0'
        option log_proto 'udp'
        option conloglevel '8'
        option cronloglevel '5'
        option compat_version '1.1'
config timeserver 'ntp'
        option enabled '1'
        option enable_server '1'
        option interface 'server'
        option interface 'things'
        list server '0.openwrt.pool.ntp.org'
        list server '1.openwrt.pool.ntp.org'
        list server '2.openwrt.pool.ntp.org'
        list server '3.openwrt.pool.ntp.org'
EOF

EOF

cat > "/etc/sysctl.conf" << 'EOF'
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
EOF

cat > "/root/initiate" << 'EOF'
#!/bin/sh
opkg update
opkg install tailscale jq
tailscale up --ssh --force-reauth --auth-key="$AUTH_KEY" --advertise-exit-node --advertise-routes=192.168.11.0/24,192.168.21.0/24,192.168.31.0/24 --hostname=axt
EOF

chmod +x "/root/initiate"

cat > "/etc/crontabs/root" << EOF
@reboot /root/initiate
EOF
reboot
